ALTER TABLE "Route"
ADD COLUMN "routeKind" TEXT NOT NULL DEFAULT 'LUBRICATION';

ALTER TABLE "Route"
ALTER COLUMN "lubricantType" DROP NOT NULL;

ALTER TABLE "Route"
ALTER COLUMN "quantity" DROP NOT NULL;
